env:
  secure: 0O435kt/v25XtJ9oc19xoVEwr7YaispQoARF017y3yvt12ee6WRalslQnNdoMStJJ9ROrKtEhANq+R/IrrNuFTF50HEjeMUnk1j30Yt1tyYw1v88Y0Pi3CMfRHkK5upLFvSnrgZJXj3iCsCDVXY3BaWlJTpyZlKahrXi9hGakHGqGHAPf/Y7wiBeAvuZyxAjoy3nQQHdDiOjQU9DYusXiAaSZylm6ZR+Hj0RF0DO20zzTfFZOoLU4OD+MQWckPhF/8im7tiZ6msINCSA94P2PpDnQQH1SPahhuAm14sb/sj056N/kGPj9sydH1Ll6NgJZrymk9Al6ernHW8z5HWr7TWgD5LcpDXJ0sPJsqIx7heQ4JfFkMv96DPH94Sa/OEcVaOO1bqOtMAVIyqXKKk8s+Z4/JLg3D46RakbYojKGn1nM1JttTGLxsz/IRVvl2zsG4xB8mNPcEbK6yYqI1EjaP5lc2PeuQS6hWsP8oIv+lEbXhQs9da5cJMAdE/ayIOEQrt4S+47QzMwQoeKRI0/bcrmXoA4Ur4lq5ZUV89j4D89V+uLADYCkcWQehi/Nm3LUHLqodlBKOGm+En7pumMEPGtYIbHsk0uF/Jr+U2D6T3OmlEv2f09S/l3bT2flS8939M2DfPSbg2dK1AXG04O96CQM5jZ/hh+4a56HQoD6Lc=
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script: mvn clean deploy -DSONATYPE_PASSWORD=$SONATYPE_PASSWORD -f ./nativedependencies-maven-plugin/pom.xml --settings .travis/settings.xml -DskipTests=true -Pgpgsign -B -U
